export const CRITICAL_KEYWORDS = [
  // English
  "weapon",
  "gun",
  "firearm",
  "knife",
  "blade",
  "machete",
  "stab",
  "stabbing",
  "shooting",
  "gunfire",
  "shot",
  "explosion",
  "bomb",
  "grenade",
  "fire",
  "burning",
  "arson",
  "bleeding",
  "unconscious",
  "collapsed",
  "dying",
  "severely injured",
  "gunshot wound",
  "critical",
  "fainted",
  "life-threatening",

  // Tagalog
  "baril",
  "bomba",
  "granada",
  "patalim",
  "saksak",
  "nasaksak",
  "binaril",
  "nasunog",
  "sunog",
  "nagbabaga",
  "nahimatay",
  "wala sa malay",
  "malubhang sugat",
  "dumudugo",
  "delikado",
  "nasugatan",
  "nanghihina",
];

export const SERIOUS_KEYWORDS = [
  // English
  "threat",
  "threatened",
  "danger",
  "assault",
  "attacked",
  "beaten",
  "fighting",
  "brawl",
  "choking",
  "screaming",
  "yelling",
  "domestic violence",
  "harassment",
  "molested",
  "abused",
  "kidnapped",
  "missing person",
  "breaking in",
  "trespassing",
  "stalker",
  "robbery",
  "rape",
  "sexual assault",

  // Tagalog
  "banta",
  "binantaan",
  "panganib",
  "inaatake",
  "inaway",
  "sinaktan",
  "binugbog",
  "nag-aaway",
  "sinisigawan",
  "sumisigaw",
  "hinihila",
  "sinisindak",
  "pang-aabuso",
  "nireklamo",
  "pinasok ang bahay",
  "ninanakawan",
  "nire-rape",
  "ginalaw",
  "nawawala",
  "dinukot",
];

export const TRIVIAL_KEYWORDS = [
  // English
  "already solved",
  "solved",
  "settled",
  "apology",
  "apologized",
  "false alarm",
  "minor",
  "small issue",
  "not urgent",
  "handled",
  "nothing happened",
  "no longer a problem",
  "just noise",
  "neighbors fighting",
  "nothing serious",
  "misunderstanding",

  // Tagalog
  "ayos na",
  "naresolba",
  "pasensya",
  "nag-sorry",
  "hindi totoo",
  "maliit na bagay",
  "hindi emergency",
  "natapos na",
  "wala nang problema",
  "ingay lang",
  "nag-aaway lang",
  "hindi malala",
  "hindi grabe",
  "kalituhan",
];

export const MISUSE_KEYWORDS = [
  // English
  "joke",
  "prank",
  "test",
  "trial",
  "spam",
  "not real",
  "just kidding",
  "messing around",
  "troll",
  "practice",
  "fake report",
  "false report",
  "made up",
  "no incident",
  "imaginary",
  "for fun",

  // Tagalog
  "biro",
  "joke lang",
  "testing lang",
  "spam lang",
  "hindi totoo",
  "kunwari lang",
  "imbento lang",
  "wala naman nangyari",
  "trip lang",
  "nag-eexperiment",
  "naglalaro lang",
  "kalokohan",
  "walang basehan",
];

export const KEYWORD_GROUPS = {
  critical: { keywords: CRITICAL_KEYWORDS, weight: 5 },
  serious: { keywords: SERIOUS_KEYWORDS, weight: 4 },
  trivial: { keywords: TRIVIAL_KEYWORDS, weight: 2 },
  misuse: { keywords: MISUSE_KEYWORDS, weight: 1 },
};
