-- AlterTable
ALTER TABLE `blotter` MODIFY `category` ENUM('NOISE_COMPLAINT', 'THEFT_OR_BURGLARY', 'TRESPASSING', 'DISTURBANCE_OF_PEACE', 'ASSAULT', 'TRAFFIC_INCIDENT', 'DISORDERLY_CONDUCT', 'PROPERTY_DAMAGE', 'SUSPICIOUS_ACTIVITY', 'DOMESTIC_VIOLENCE', 'ACCIDENT', 'ANIMAL_COMPLAINT', 'DRUG_RELATED', 'FIRE', 'FRAUD', 'HARASSMENT', 'ILLEGAL_STRUCTURE', 'LOST_AND_FOUND', 'MISSING_PERSON', 'VANDALISM', 'PUBLIC_DISTURBANCE', 'VIOLATION_OF_ORDINANCE', 'WEAPONS_OFFENSE', 'OTHER') NOT NULL;

-- AlterTable
ALTER TABLE `complaint` ADD COLUMN `severity` ENUM('EMERGENCY', 'URGENT', 'MODERATE', 'MINOR', 'INFORMATIONAL') NULL,
    MODIFY `category` ENUM('NOISE_COMPLAINT', 'THEFT_OR_BURGLARY', 'TRESPASSING', 'DISTURBANCE_OF_PEACE', 'ASSAULT', 'TRAFFIC_INCIDENT', 'DISORDERLY_CONDUCT', 'PROPERTY_DAMAGE', 'SUSPICIOUS_ACTIVITY', 'DOMESTIC_VIOLENCE', 'ACCIDENT', 'ANIMAL_COMPLAINT', 'DRUG_RELATED', 'FIRE', 'FRAUD', 'HARASSMENT', 'ILLEGAL_STRUCTURE', 'LOST_AND_FOUND', 'MISSING_PERSON', 'VANDALISM', 'PUBLIC_DISTURBANCE', 'VIOLATION_OF_ORDINANCE', 'WEAPONS_OFFENSE', 'OTHER') NOT NULL;
