export const CATEGORIES = {
  "Accident": "ACCIDENT",
  "Animal Complaint": "ANIMAL_COMPLAINT",
  "Assault": "ASSAULT",
  "Disorderly Conduct": "DISORDERLY_CONDUCT",
  "Disturbance of Peace": "DISTURBANCE_OF_PEACE",
  "Domestic Violence": "DOMESTIC_VIOLENCE",
  "Drug Related": "DRUG_RELATED",
  "Fire": "FIRE",
  "Fraud": "FRAUD",
  "Harassment": "HARASSMENT",
  "Illegal Structure": "ILLEGAL_STRUCTURE",
  "Lost and Found": "LOST_AND_FOUND",
  "Missing Person": "MISSING_PERSON",
  "Noise Complaint": "NOISE_COMPLAINT",
  "Property Damage / Vandalism": "VANDALISM",
  "Public Disturbance": "PUBLIC_DISTURBANCE",
  "Suspicious Activity": "SUSPICIOUS_ACTIVITY",
  "Theft or Burglary": "THEFT",
  "Traffic Incident": "TRAFFIC_INCIDENT",
  "Trespassing": "TRESPASSING",
  "Violation of Ordinance": "VIOLATION_OF_ORDINANCE",
  "Weapons Offense": "WEAPONS_OFFENSE",
  "Other": "OTHER",
};
